// BANCO DE DADOS: UEFA CHAMPIONS LEAGUE (EXPANDIDO)
// js/atletas/champions_league.js
// ==================================================

const championsLeague = [
    // 🧤 GOLEIROS (20)
    { nome: "Thibaut Courtois (Real Madrid)", posicao: "Goleiro", nota: 92 },
    { nome: "Alisson Becker (Liverpool)", posicao: "Goleiro", nota: 90 },
    { nome: "Marc-André ter Stegen (Barcelona)", posicao: "Goleiro", nota: 90 },
    { nome: "Gianluigi Donnarumma (Manchester City)", posicao: "Goleiro", nota: 89 },
    { nome: "David Raya (Arsenal)", posicao: "Goleiro", nota: 89 },
    { nome: "Jan Oblak (Atlético de Madrid)", posicao: "Goleiro", nota: 89 },
    { nome: "Mike Maignan (Milan)", posicao: "Goleiro", nota: 89 },
    { nome: "Gregor Kobel (Borussia Dortmund)", posicao: "Goleiro", nota: 88 },
    { nome: "Yann Sommer (Inter de Milão)", posicao: "Goleiro", nota: 88 },
    { nome: "Emiliano Martínez (Aston Villa)", posicao: "Goleiro", nota: 88 },
    { nome: "Manuel Neuer (Bayern de Munique)", posicao: "Goleiro", nota: 87 },
    { nome: "Guglielmo Vicario (Tottenham)", posicao: "Goleiro", nota: 86 },
    { nome: "Lucas Chevalier (Lille)", posicao: "Goleiro", nota: 86 },
    { nome: "Alex Meret (Napoli)", posicao: "Goleiro", nota: 85 },
    { nome: "Michele Di Gregorio (Juventus)", posicao: "Goleiro", nota: 85 },
    { nome: "Diogo Costa (Porto)", posicao: "Goleiro", nota: 85 },
    { nome: "Anatoliy Trubin (Benfica)", posicao: "Goleiro", nota: 85 },
    { nome: "Robert Sánchez (Chelsea)", posicao: "Goleiro", nota: 84 },
    { nome: "Péter Gulácsi (RB Leipzig)", posicao: "Goleiro", nota: 84 },
    { nome: "Walter Benítez (PSV Eindhoven)", posicao: "Goleiro", nota: 83 },

    // 🛡️ ZAGUEIROS / DEFENSORES (20)
    { nome: "Virgil van Dijk (Liverpool)", posicao: "Zagueiro", nota: 91 },
    { nome: "William Saliba (Arsenal)", posicao: "Zagueiro", nota: 90 },
    { nome: "Rúben Dias (Manchester City)", posicao: "Zagueiro", nota: 90 },
    { nome: "Antonio Rüdiger (Real Madrid)", posicao: "Zagueiro", nota: 90 },
    { nome: "Alessandro Bastoni (Inter de Milão)", posicao: "Zagueiro", nota: 89 },
    { nome: "Marquinhos (Paris Saint-Germain)", posicao: "Zagueiro", nota: 89 },
    { nome: "Gabriel Magalhães (Arsenal)", posicao: "Zagueiro", nota: 88 },
    { nome: "Joško Gvardiol (Manchester City)", posicao: "Zagueiro", nota: 88 },
    { nome: "Dayot Upamecano (Bayern de Munique)", posicao: "Zagueiro", nota: 88 },
    { nome: "Achraf Hakimi (Paris Saint-Germain)", posicao: "Zagueiro", nota: 88 },
    { nome: "Éder Militão (Real Madrid)", posicao: "Zagueiro", nota: 88 },
    { nome: "Theo Hernández (Milan)", posicao: "Zagueiro", nota: 88 },
    { nome: "Jules Koundé (Barcelona)", posicao: "Zagueiro", nota: 88 },
    { nome: "Alphonso Davies (Bayern de Munique)", posicao: "Zagueiro", nota: 88 },
    { nome: "Micky van de Ven (Tottenham)", posicao: "Zagueiro", nota: 87 },
    { nome: "Gleison Bremer (Juventus)", posicao: "Zagueiro", nota: 87 },
    { nome: "Pau Cubarsí (Barcelona)", posicao: "Zagueiro", nota: 87 },
    { nome: "Willian Pacho (Paris Saint-Germain)", posicao: "Zagueiro", nota: 87 },
    { nome: "Nico Schlotterbeck (Borussia Dortmund)", posicao: "Zagueiro", nota: 87 },
    { nome: "Federico Dimarco (Inter de Milão)", posicao: "Zagueiro", nota: 87 },

    // 🎯 MEIAS (40)
    { nome: "Jude Bellingham (Real Madrid)", posicao: "Meia", nota: 95 },
    { nome: "Rodri (Barcelona)", posicao: "Meia", nota: 94 },
    { nome: "Federico Valverde (Real Madrid)", posicao: "Meia", nota: 93 },
    { nome: "Pedri (Barcelona)", posicao: "Meia", nota: 93 },
    { nome: "Phil Foden (Manchester City)", posicao: "Meia", nota: 92 },
    { nome: "Martin Ødegaard (Arsenal)", posicao: "Meia", nota: 92 },
    { nome: "Cole Palmer (Chelsea)", posicao: "Meia", nota: 92 },
    { nome: "Jamal Musiala (Bayern de Munique)", posicao: "Meia", nota: 92 },
    { nome: "Eduardo Camavinga (Real Madrid)", posicao: "Meia", nota: 91 },
    { nome: "Declan Rice (Arsenal)", posicao: "Meia", nota: 91 },
    { nome: "Aurélien Tchouaméni (Real Madrid)", posicao: "Meia", nota: 91 },
    { nome: "Nicolò Barella (Inter de Milão)", posicao: "Meia", nota: 91 },
    { nome: "Alexis Mac Allister (Liverpool)", posicao: "Meia", nota: 90 },
    { nome: "Florian Wirtz (Liverpool)", posicao: "Meia", nota: 90 },
    { nome: "Gavi (Barcelona)", posicao: "Meia", nota: 90 },
    { nome: "Joshua Kimmich (Bayern de Munique)", posicao: "Meia", nota: 90 },
    { nome: "Moisés Caicedo (Chelsea)", posicao: "Meia", nota: 89 },
    { nome: "Bruno Guimarães (Arsenal)", posicao: "Meia", nota: 89 },
    { nome: "Frenkie de Jong (Barcelona)", posicao: "Meia", nota: 89 },
    { nome: "Hakan Çalhanoğlu (Inter de Milão)", posicao: "Meia", nota: 89 },
    { nome: "Dominik Szoboszlai (Liverpool)", posicao: "Meia", nota: 88 },
    { nome: "Enzo Fernández (Chelsea)", posicao: "Meia", nota: 88 },
    { nome: "Dejan Kulusevski (Tottenham)", posicao: "Meia", nota: 88 },
    { nome: "Teun Koopmeiners (Juventus)", posicao: "Meia", nota: 88 },
    { nome: "Vitinha (Paris Saint-Germain)", posicao: "Meia", nota: 88 },
    { nome: "Dani Olmo (Barcelona)", posicao: "Meia", nota: 88 },
    { nome: "Fabián Ruiz (Paris Saint-Germain)", posicao: "Meia", nota: 87 },
    { nome: "James Maddison (Tottenham)", posicao: "Meia", nota: 87 },
    { nome: "Warren Zaïre-Emery (Paris Saint-Germain)", posicao: "Meia", nota: 87 },
    { nome: "Eberechi Eze (Crystal Palace)", posicao: "Meia", nota: 87 },
    { nome: "Aleksandar Pavlović (Bayern de Munique)", posicao: "Meia", nota: 86 },
    { nome: "Ryan Gravenberch (Liverpool)", posicao: "Meia", nota: 86 },
    { nome: "Sandro Tonali (Tottenham)", posicao: "Meia", nota: 86 },
    { nome: "Arda Güler (Real Madrid)", posicao: "Meia", nota: 86 },
    { nome: "Fermín López (Barcelona)", posicao: "Meia", nota: 86 },
    { nome: "Xavi Simons (RB Leipzig)", posicao: "Meia", nota: 86 },
    { nome: "Manuel Locatelli (Juventus)", posicao: "Meia", nota: 85 },
    { nome: "João Neves (Paris Saint-Germain)", posicao: "Meia", nota: 85 },
    { nome: "Marcel Sabitzer (Borussia Dortmund)", posicao: "Meia", nota: 85 },
    { nome: "Stanislav Lobotka (Napoli)", posicao: "Meia", nota: 85 },

    // ⚽ ATACANTES (20)
    { nome: "Kylian Mbappé (Real Madrid)", posicao: "Atacante", nota: 97 },
    { nome: "Vinícius Júnior (Real Madrid)", posicao: "Atacante", nota: 96 },
    { nome: "Erling Haaland (Manchester City)", posicao: "Atacante", nota: 96 },
    { nome: "Harry Kane (Bayern de Munique)", posicao: "Atacante", nota: 95 },
    { nome: "Lamine Yamal (Barcelona)", posicao: "Atacante", nota: 94 },
    { nome: "Bukayo Saka (Arsenal)", posicao: "Atacante", nota: 93 },
    { nome: "Lautaro Martínez (Inter de Milão)", posicao: "Atacante", nota: 92 },
    { nome: "Rodrygo (Real Madrid)", posicao: "Atacante", nota: 91 },
    { nome: "Viktor Gyökeres (Arsenal)", posicao: "Atacante", nota: 91 },
    { nome: "Robert Lewandowski (Barcelona)", posicao: "Atacante", nota: 90 },
    { nome: "Alexander Isak (Liverpool)", posicao: "Atacante", nota: 90 },
    { nome: "Raphinha (Barcelona)", posicao: "Atacante", nota: 90 },
    { nome: "Antoine Griezmann (Atlético de Madrid)", posicao: "Atacante", nota: 90 },
    { nome: "Ousmane Dembélé (Paris Saint-Germain)", posicao: "Atacante", nota: 89 },
    { nome: "Rafael Leão (Milan)", posicao: "Atacante", nota: 89 },
    { nome: "Khvicha Kvaratskhelia (Napoli)", posicao: "Atacante", nota: 89 },
    { nome: "Julián Álvarez (Atlético de Madrid)", posicao: "Atacante", nota: 89 },
    { nome: "Cody Gakpo (Liverpool)", posicao: "Atacante", nota: 88 },
    { nome: "Kai Havertz (Arsenal)", posicao: "Atacante", nota: 88 },
    { nome: "Serhou Guirassy (Borussia Dortmund)", posicao: "Atacante", nota: 87 }
];