// BANCO DE DADOS: LENDAS DO FUTEBOL (EXPANDIDO)
// js/atletas/lendas.js
// ==================================================

const lendas = [
    // 🧤 GOLEIROS (20)
    { nome: "Lev Yashin (União Soviética)", posicao: "Goleiro", nota: 98 },
    { nome: "Gianluigi Buffon (Itália)", posicao: "Goleiro", nota: 96 },
    { nome: "Manuel Neuer (Alemanha)", posicao: "Goleiro", nota: 96 },
    { nome: "Rogério Ceni (Brasil)", posicao: "Goleiro", nota: 96 },
    { nome: "Gordon Banks (Inglaterra)", posicao: "Goleiro", nota: 95 },
    { nome: "Dino Zoff (Itália)", posicao: "Goleiro", nota: 95 },
    { nome: "Iker Casillas (Espanha)", posicao: "Goleiro", nota: 95 },
    { nome: "Peter Schmeichel (Dinamarca)", posicao: "Goleiro", nota: 95 },
    { nome: "Sepp Maier (Alemanha)", posicao: "Goleiro", nota: 94 },
    { nome: "Oliver Kahn (Alemanha)", posicao: "Goleiro", nota: 94 },
    { nome: "Petr Čech (República Tcheca)", posicao: "Goleiro", nota: 94 },
    { nome: "Gylmar dos Santos Neves (Brasil)", posicao: "Goleiro", nota: 94 },
    { nome: "Cláudio Taffarel (Brasil)", posicao: "Goleiro", nota: 93 },
    { nome: "Dida (Brasil)", posicao: "Goleiro", nota: 93 },
    { nome: "Júlio César (Brasil)", posicao: "Goleiro", nota: 93 },
    { nome: "Edwin van der Sar (Holanda)", posicao: "Goleiro", nota: 92 },
    { nome: "José Luis Chilavert (Paraguai)", posicao: "Goleiro", nota: 92 },
    { nome: "Amadeo Carrizo (Argentina)", posicao: "Goleiro", nota: 91 },
    { nome: "Marcos (Brasil)", posicao: "Goleiro", nota: 91 },
    { nome: "Ubaldo Fillol (Argentina)", posicao: "Goleiro", nota: 91 },

    // 🛡️ ZAGUEIROS / DEFENSORES (20)
    { nome: "Franz Beckenbauer (Alemanha)", posicao: "Zagueiro", nota: 98 },
    { nome: "Paolo Maldini (Itália)", posicao: "Zagueiro", nota: 97 },
    { nome: "Franco Baresi (Itália)", posicao: "Zagueiro", nota: 96 },
    { nome: "Fabio Cannavaro (Itália)", posicao: "Zagueiro", nota: 96 },
    { nome: "Sergio Ramos (Espanha)", posicao: "Zagueiro", nota: 96 },
    { nome: "Bobby Moore (Inglaterra)", posicao: "Zagueiro", nota: 95 },
    { nome: "Elías Figueroa (Chile)", posicao: "Zagueiro", nota: 95 },
    { nome: "Carlos Alberto Torres (Brasil)", posicao: "Zagueiro", nota: 95 },
    { nome: "Nilton Santos (Brasil)", posicao: "Zagueiro", nota: 95 },
    { nome: "Gaetano Scirea (Itália)", posicao: "Zagueiro", nota: 95 },
    { nome: "Alessandro Nesta (Itália)", posicao: "Zagueiro", nota: 95 },
    { nome: "Roberto Carlos (Brasil)", posicao: "Zagueiro", nota: 95 },
    { nome: "Daniel Passarella (Argentina)", posicao: "Zagueiro", nota: 94 },
    { nome: "Carles Puyol (Espanha)", posicao: "Zagueiro", nota: 94 },
    { nome: "Djalma Santos (Brasil)", posicao: "Zagueiro", nota: 94 },
    { nome: "Cafu (Brasil)", posicao: "Zagueiro", nota: 94 },
    { nome: "Ruud Krol (Holanda)", posicao: "Zagueiro", nota: 94 },
    { nome: "Domingos da Guia (Brasil)", posicao: "Zagueiro", nota: 93 },
    { nome: "Hilderaldo Bellini (Brasil)", posicao: "Zagueiro", nota: 92 },
    { nome: "Mauro Ramos de Oliveira (Brasil)", posicao: "Zagueiro", nota: 92 },

    // 🎯 MEIAS (40)
    { nome: "Diego Maradona (Argentina)", posicao: "Meia", nota: 99 },
    { nome: "Alfredo Di Stéfano (Argentina)", posicao: "Meia", nota: 98 },
    { nome: "Johan Cruyff (Holanda)", posicao: "Meia", nota: 98 },
    { nome: "Zinedine Zidane (França)", posicao: "Meia", nota: 98 },
    { nome: "Ronaldinho Gaúcho (Brasil)", posicao: "Meia", nota: 98 },
    { nome: "Zico (Brasil)", posicao: "Meia", nota: 98 },
    { nome: "Michel Platini (França)", posicao: "Meia", nota: 97 },
    { nome: "Zizinho (Brasil)", posicao: "Meia", nota: 97 },
    { nome: "Rivaldo (Brasil)", posicao: "Meia", nota: 97 },
    { nome: "Lothar Matthäus (Alemanha)", posicao: "Meia", nota: 96 },
    { nome: "Bobby Charlton (Inglaterra)", posicao: "Meia", nota: 96 },
    { nome: "Luka Modrić (Croácia)", posicao: "Meia", nota: 96 },
    { nome: "Didi (Brasil)", posicao: "Meia", nota: 96 },
    { nome: "Kaká (Brasil)", posicao: "Meia", nota: 96 },
    { nome: "Tostão (Brasil)", posicao: "Meia", nota: 96 },
    { nome: "Andrés Iniesta (Espanha)", posicao: "Meia", nota: 95 },
    { nome: "Xavi Hernández (Espanha)", posicao: "Meia", nota: 95 },
    { nome: "Ruud Gullit (Holanda)", posicao: "Meia", nota: 95 },
    { nome: "Roberto Rivelino (Brasil)", posicao: "Meia", nota: 95 },
    { nome: "Luis Suárez Miramontes (Espanha)", posicao: "Meia", nota: 95 },
    { nome: "Raymond Kopa (França)", posicao: "Meia", nota: 95 },
    { nome: "Sócrates (Brasil)", posicao: "Meia", nota: 94 },
    { nome: "Gérson (Brasil)", posicao: "Meia", nota: 94 },
    { nome: "Paulo Roberto Falcão (Brasil)", posicao: "Meia", nota: 94 },
    { nome: "Ademir da Guia (Brasil)", posicao: "Meia", nota: 94 },
    { nome: "Dirceu Lopes (Brasil)", posicao: "Meia", nota: 94 },
    { nome: "Enzo Francescoli (Uruguai)", posicao: "Meia", nota: 94 },
    { nome: "Teófilo Cubillas (Peru)", posicao: "Meia", nota: 94 },
    { nome: "Gheorghe Hagi (Romênia)", posicao: "Meia", nota: 94 },
    { nome: "Michael Laudrup (Dinamarca)", posicao: "Meia", nota: 94 },
    { nome: "Toni Kroos (Alemanha)", posicao: "Meia", nota: 94 },
    { nome: "Andrea Pirlo (Itália)", posicao: "Meia", nota: 94 },
    { nome: "Steven Gerrard (Inglaterra)", posicao: "Meia", nota: 94 },
    { nome: "Frank Rijkaard (Holanda)", posicao: "Meia", nota: 93 },
    { nome: "Gianni Rivera (Itália)", posicao: "Meia", nota: 93 },
    { nome: "Pavel Nedvěd (República Tcheca)", posicao: "Meia", nota: 93 },
    { nome: "Juan Román Riquelme (Argentina)", posicao: "Meia", nota: 93 },
    { nome: "Fernando Redondo (Argentina)", posicao: "Meia", nota: 93 },
    { nome: "Toninho Cerezo (Brasil)", posicao: "Meia", nota: 93 },
    { nome: "Carlos Valderrama (Colômbia)", posicao: "Meia", nota: 92 },

    // ⚽ ATACANTES (20)
    { nome: "Pelé (Brasil)", posicao: "Atacante", nota: 100 },
    { nome: "Lionel Messi (Argentina)", posicao: "Atacante", nota: 99 },
    { nome: "Cristiano Ronaldo (Portugal)", posicao: "Atacante", nota: 99 },
    { nome: "Ronaldo Fenômeno (Brasil)", posicao: "Atacante", nota: 98 },
    { nome: "Romário (Brasil)", posicao: "Atacante", nota: 98 },
    { nome: "Garrincha (Brasil)", posicao: "Atacante", nota: 98 },
    { nome: "Ferenc Puskás (Hungria)", posicao: "Atacante", nota: 97 },
    { nome: "Eusébio (Portugal)", posicao: "Atacante", nota: 97 },
    { nome: "Marco van Basten (Holanda)", posicao: "Atacante", nota: 97 },
    { nome: "Thierry Henry (França)", posicao: "Atacante", nota: 97 },
    { nome: "Luis Suárez (Uruguai)", posicao: "Atacante", nota: 96 },
    { nome: "Adriano Imperador (Brasil)", posicao: "Atacante", nota: 96 },
    { nome: "Gerd Müller (Alemanha)", posicao: "Atacante", nota: 96 },
    { nome: "Roberto Baggio (Itália)", posicao: "Atacante", nota: 96 },
    { nome: "Andriy Shevchenko (Ucrânia)", posicao: "Atacante", nota: 95 },
    { nome: "Zlatan Ibrahimović (Suécia)", posicao: "Atacante", nota: 95 },
    { nome: "George Best (Irlanda do Norte)", posicao: "Atacante", nota: 95 },
    { nome: "Wayne Rooney (Inglaterra)", posicao: "Atacante", nota: 94 },
    { nome: "Samuel Eto'o (Camarões)", posicao: "Atacante", nota: 94 },
    { nome: "Didier Drogba (Costa do Marfim)", posicao: "Atacante", nota: 94 }
];