const nostalgia = [
    // 🧤 GOLEIROS (20)
    { nome: "Rogério Ceni (São Paulo 2005)", posicao: "Goleiro", nota: 96 },
    { nome: "Gianluigi Buffon (Juventus 2006)", posicao: "Goleiro", nota: 96 },
    { nome: "Manuel Neuer (Alemanha 2014)", posicao: "Goleiro", nota: 96 },
    { nome: "Iker Casillas (Real Madrid 2008)", posicao: "Goleiro", nota: 95 },
    { nome: "Peter Schmeichel (Manchester United 1999)", posicao: "Goleiro", nota: 95 },
    { nome: "Petr Čech (Chelsea 2005)", posicao: "Goleiro", nota: 94 },
    { nome: "Oliver Kahn (Bayern de Munique 2001)", posicao: "Goleiro", nota: 94 },
    { nome: "Dida (Milan 2003)", posicao: "Goleiro", nota: 93 },
    { nome: "Júlio César (Inter de Milão 2010)", posicao: "Goleiro", nota: 93 },
    { nome: "Cláudio Taffarel (Brasil 1994)", posicao: "Goleiro", nota: 93 },
    { nome: "Edwin van der Sar (Manchester United 2008)", posicao: "Goleiro", nota: 92 },
    { nome: "José Luis Chilavert (Vélez Sarsfield 1998)", posicao: "Goleiro", nota: 92 },
    { nome: "Marcos (Palmeiras 2002)", posicao: "Goleiro", nota: 91 },
    { nome: "Francesco Toldo (Itália 2000)", posicao: "Goleiro", nota: 91 },
    { nome: "Santiago Cañizares (Valencia 2001)", posicao: "Goleiro", nota: 90 },
    { nome: "Victor Valdés (Barcelona 2009)", posicao: "Goleiro", nota: 89 },
    { nome: "David Seaman (Arsenal 1998)", posicao: "Goleiro", nota: 89 },
    { nome: "Danrlei (Grêmio 1995)", posicao: "Goleiro", nota: 89 },
    { nome: "Fabien Barthez (França 2000)", posicao: "Goleiro", nota: 88 },
    { nome: "Jens Lehmann (Arsenal 2004)", posicao: "Goleiro", nota: 88 },

    // 🛡️ ZAGUEIROS / DEFENSORES (20)
    { nome: "Paolo Maldini (Milan 2003)", posicao: "Zagueiro", nota: 97 },
    { nome: "Fabio Cannavaro (Itália 2006)", posicao: "Zagueiro", nota: 96 },
    { nome: "Sergio Ramos (Real Madrid 2014)", posicao: "Zagueiro", nota: 96 },
    { nome: "Alessandro Nesta (Milan 2005)", posicao: "Zagueiro", nota: 95 },
    { nome: "Carles Puyol (Barcelona 2009)", posicao: "Zagueiro", nota: 94 },
    { nome: "Roberto Carlos (Real Madrid 2002)", posicao: "Zagueiro", nota: 94 },
    { nome: "Daniel Alves (Barcelona 2011)", posicao: "Zagueiro", nota: 94 },
    { nome: "Rio Ferdinand (Manchester United 2008)", posicao: "Zagueiro", nota: 93 },
    { nome: "John Terry (Chelsea 2005)", posicao: "Zagueiro", nota: 93 },
    { nome: "Cafu (Milan 2005)", posicao: "Zagueiro", nota: 93 },
    { nome: "Javier Zanetti (Inter de Milão 2010)", posicao: "Zagueiro", nota: 93 },
    { nome: "Lilian Thuram (França 1998)", posicao: "Zagueiro", nota: 93 },
    { nome: "Marcelo (Real Madrid 2017)", posicao: "Zagueiro", nota: 93 },
    { nome: "Nemanja Vidić (Manchester United 2009)", posicao: "Zagueiro", nota: 92 },
    { nome: "Lúcio (Inter de Milão 2010)", posicao: "Zagueiro", nota: 92 },
    { nome: "Carlos Gamarra (Corinthians 1998)", posicao: "Zagueiro", nota: 91 },
    { nome: "Aldair (Roma 2001)", posicao: "Zagueiro", nota: 91 },
    { nome: "Mauro Galvão (Vasco 1998)", posicao: "Zagueiro", nota: 91 },
    { nome: "Jaap Stam (Milan 2005)", posicao: "Zagueiro", nota: 90 },
    { nome: "Lugano (São Paulo 2005)", posicao: "Zagueiro", nota: 89 },

    // 🎯 MEIAS (30)
    { nome: "Zinedine Zidane (Real Madrid 2002)", posicao: "Meia", nota: 98 },
    { nome: "Ronaldinho Gaúcho (Barcelona 2005)", posicao: "Meia", nota: 98 },
    { nome: "Kaká (Milan 2007)", posicao: "Meia", nota: 97 },
    { nome: "Rivaldo (Barcelona 1999)", posicao: "Meia", nota: 97 },
    { nome: "Luka Modrić (Real Madrid 2018)", posicao: "Meia", nota: 96 },
    { nome: "Andrés Iniesta (Barcelona 2009)", posicao: "Meia", nota: 95 },
    { nome: "Xavi Hernández (Barcelona 2009)", posicao: "Meia", nota: 95 },
    { nome: "Andrea Pirlo (Milan 2006)", posicao: "Meia", nota: 94 },
    { nome: "Steven Gerrard (Liverpool 2005)", posicao: "Meia", nota: 94 },
    { nome: "Toni Kroos (Real Madrid 2017)", posicao: "Meia", nota: 94 },
    { nome: "Sergio Busquets (Barcelona 2011)", posicao: "Meia", nota: 94 },
    { nome: "Frank Lampard (Chelsea 2005)", posicao: "Meia", nota: 93 },
    { nome: "Paul Scholes (Manchester United 2008)", posicao: "Meia", nota: 93 },
    { nome: "Patrick Vieira (Arsenal 2004)", posicao: "Meia", nota: 93 },
    { nome: "Pavel Nedvěd (Juventus 2003)", posicao: "Meia", nota: 93 },
    { nome: "Juan Román Riquelme (Boca Juniors 2007)", posicao: "Meia", nota: 93 },
    { nome: "Clarence Seedorf (Milan 2007)", posicao: "Meia", nota: 92 },
    { nome: "Juninho Pernambucano (Lyon 2006)", posicao: "Meia", nota: 92 },
    { nome: "David Beckham (Manchester United 1999)", posicao: "Meia", nota: 92 },
    { nome: "Roy Keane (Manchester United 1999)", posicao: "Meia", nota: 92 },
    { nome: "Raí (São Paulo 1992)", posicao: "Meia", nota: 92 },
    { nome: "Michael Ballack (Bayern de Munique 2002)", posicao: "Meia", nota: 91 },
    { nome: "Deco (Porto 2004)", posicao: "Meia", nota: 91 },
    { nome: "Alex Cabeção (Cruzeiro 2003)", posicao: "Meia", nota: 91 },
    { nome: "Claude Makélélé (Chelsea 2005)", posicao: "Meia", nota: 91 },
    { nome: "Edgar Davids (Juventus 1998)", posicao: "Meia", nota: 91 },
    { nome: "Gennaro Gattuso (Milan 2007)", posicao: "Meia", nota: 90 },
    { nome: "Diego Ribas (Santos 2002)", posicao: "Meia", nota: 90 },
    { nome: "Danilo (São Paulo 2005)", posicao: "Meia", nota: 90 },
    { nome: "Dejan Stanković (Inter de Milão 2010)", posicao: "Meia", nota: 89 },

    // ⚽ ATACANTES (20)
    { nome: "Lionel Messi (Barcelona 2012)", posicao: "Atacante", nota: 99 },
    { nome: "Cristiano Ronaldo (Real Madrid 2017)", posicao: "Atacante", nota: 99 },
    { nome: "Ronaldo Fenômeno (Inter/Real 2002)", posicao: "Atacante", nota: 98 },
    { nome: "Romário (Barcelona 1994)", posicao: "Atacante", nota: 98 },
    { nome: "Thierry Henry (Arsenal 2004)", posicao: "Atacante", nota: 97 },
    { nome: "Adriano Imperador (Inter de Milão 2005)", posicao: "Atacante", nota: 96 },
    { nome: "Luis Suárez (Barcelona 2016)", posicao: "Atacante", nota: 96 },
    { nome: "Andriy Shevchenko (Milan 2004)", posicao: "Atacante", nota: 95 },
    { nome: "Zlatan Ibrahimović (Inter/PSG 2012)", posicao: "Atacante", nota: 95 },
    { nome: "Wayne Rooney (Manchester United 2008)", posicao: "Atacante", nota: 94 },
    { nome: "Samuel Eto'o (Barcelona 2006)", posicao: "Atacante", nota: 94 },
    { nome: "Didier Drogba (Chelsea 2007)", posicao: "Atacante", nota: 94 },
    { nome: "Ruud van Nistelrooy (Manchester United 2003)", posicao: "Atacante", nota: 93 },
    { nome: "Raúl González (Real Madrid 2001)", posicao: "Atacante", nota: 93 },
    { nome: "Diego Forlán (Atlético de Madrid 2010)", posicao: "Atacante", nota: 92 },
    { nome: "Filippo Inzaghi (Milan 2007)", posicao: "Atacante", nota: 92 },
    { nome: "Hernán Crespo (Inter de Milão 2005)", posicao: "Atacante", nota: 91 },
    { nome: "Michael Owen (Liverpool 2001)", posicao: "Atacante", nota: 91 },
    { nome: "Edmundo Animal (Vasco 1997)", posicao: "Atacante", nota: 90 },
    { nome: "Fred (Fluminense 2012)", posicao: "Atacante", nota: 89 }
];