const premierLeague = [
    // 🧤 GOLEIROS (12)
    { nome: "Alisson Becker (Liverpool)", posicao: "Goleiro", nota: 90 },
    { nome: "David Raya (Arsenal)", posicao: "Goleiro", nota: 89 },
    { nome: "Gianluigi Donnarumma (Manchester City)", posicao: "Goleiro", nota: 89 },
    { nome: "Emiliano Martínez (Aston Villa)", posicao: "Goleiro", nota: 88 },
    { nome: "Guglielmo Vicario (Tottenham)", posicao: "Goleiro", nota: 86 },
    { nome: "Jordan Pickford (Everton)", posicao: "Goleiro", nota: 85 },
    { nome: "André Onana (Manchester United)", posicao: "Goleiro", nota: 85 },
    { nome: "Nick Pope (Newcastle)", posicao: "Goleiro", nota: 85 },
    { nome: "Robert Sánchez (Chelsea)", posicao: "Goleiro", nota: 84 },
    { nome: "Bart Verbruggen (Brighton)", posicao: "Goleiro", nota: 84 },
    { nome: "Bernd Leno (Fulham)", posicao: "Goleiro", nota: 83 },
    { nome: "Matz Sels (Nottingham Forest)", posicao: "Goleiro", nota: 83 },

    // 🛡️ ZAGUEIROS (12)
    { nome: "Virgil van Dijk (Liverpool)", posicao: "Zagueiro", nota: 91 },
    { nome: "William Saliba (Arsenal)", posicao: "Zagueiro", nota: 90 },
    { nome: "Rúben Dias (Manchester City)", posicao: "Zagueiro", nota: 90 },
    { nome: "Gabriel Magalhães (Arsenal)", posicao: "Zagueiro", nota: 88 },
    { nome: "Joško Gvardiol (Manchester City)", posicao: "Zagueiro", nota: 88 },
    { nome: "Micky van de Ven (Tottenham)", posicao: "Zagueiro", nota: 87 },
    { nome: "Matthijs de Ligt (Manchester United)", posicao: "Zagueiro", nota: 87 },
    { nome: "Lisandro Martínez (Manchester United)", posicao: "Zagueiro", nota: 86 },
    { nome: "Reece James (Chelsea)", posicao: "Zagueiro", nota: 86 },
    { nome: "Levi Colwill (Chelsea)", posicao: "Zagueiro", nota: 86 },
    { nome: "Ezri Konsa (Aston Villa)", posicao: "Zagueiro", nota: 85 },
    { nome: "John Stones (Manchester City)", posicao: "Zagueiro", nota: 85 },
    
    // 🎯 MEIAS (20)
    { nome: "Phil Foden (Manchester City)", posicao: "Meia", nota: 92 },
    { nome: "Martin Ødegaard (Arsenal)", posicao: "Meia", nota: 92 },
    { nome: "Cole Palmer (Chelsea)", posicao: "Meia", nota: 92 },
    { nome: "Declan Rice (Arsenal)", posicao: "Meia", nota: 91 },
    { nome: "Florian Wirtz (Liverpool)", posicao: "Meia", nota: 90 },
    { nome: "Alexis Mac Allister (Liverpool)", posicao: "Meia", nota: 90 },
    { nome: "Moisés Caicedo (Chelsea)", posicao: "Meia", nota: 89 },
    { nome: "Bruno Guimarães (Arsenal)", posicao: "Meia", nota: 89 },
    { nome: "Dominik Szoboszlai (Liverpool)", posicao: "Meia", nota: 88 },
    { nome: "Enzo Fernández (Chelsea)", posicao: "Meia", nota: 88 },
    { nome: "Dejan Kulusevski (Tottenham)", posicao: "Meia", nota: 88 },
    { nome: "James Maddison (Tottenham)", posicao: "Meia", nota: 87 },
    { nome: "Eberechi Eze (Crystal Palace)", posicao: "Meia", nota: 87 },
    { nome: "Sandro Tonali (Tottenham)", posicao: "Meia", nota: 86 },
    { nome: "Youri Tielemans (Manchester United)", posicao: "Meia", nota: 86 },
    { nome: "Kobbie Mainoo (Manchester United)", posicao: "Meia", nota: 86 },
    { nome: "Ryan Gravenberch (Liverpool)", posicao: "Meia", nota: 86 },
    { nome: "João Gomes (Wolverhampton)", posicao: "Meia", nota: 85 },
    { nome: "John McGinn (Aston Villa)", posicao: "Meia", nota: 85 },
    { nome: "Morgan Gibbs-White (Nottingham Forest)", posicao: "Meia", nota: 85 },

    // ⚽ ATACANTES (12)
    { nome: "Erling Haaland (Manchester City)", posicao: "Atacante", nota: 96 },
    { nome: "Bukayo Saka (Arsenal)", posicao: "Atacante", nota: 93 },
    { nome: "Viktor Gyökeres (Arsenal)", posicao: "Atacante", nota: 91 },
    { nome: "Alexander Isak (Liverpool)", posicao: "Atacante", nota: 90 },
    { nome: "Ollie Watkins (Aston Villa)", posicao: "Atacante", nota: 89 },
    { nome: "Matheus Cunha (Manchester United)", posicao: "Atacante", nota: 89 },
    { nome: "Kai Havertz (Arsenal)", posicao: "Atacante", nota: 88 },
    { nome: "Cody Gakpo (Liverpool)", posicao: "Atacante", nota: 88 },
    { nome: "Benjamin Šeško (Manchester United)", posicao: "Atacante", nota: 88 },
    { nome: "Bryan Mbeumo (Manchester United)", posicao: "Atacante", nota: 87 },
    { nome: "Gabriel Martinelli (Arsenal)", posicao: "Atacante", nota: 87 },
    { nome: "Nicolas Jackson (Chelsea)", posicao: "Atacante", nota: 86 } 

];
